In [222]:
import pandas as pd
import gc
import os

In [223]:
orders=pd.read_csv("orders.csv")
products=pd.read_csv("products.csv")
departments=pd.read_csv("departments.csv")
aisles=pd.read_csv("aisles.csv")
prior = pd.read_csv("order_products__prior.csv")
train = pd.read_csv("order_products__train.csv")

In [211]:
print("ORDERS :",orders.shape)
print("PRODUCTS :",products.shape)
print("DEPARTMENTS :",departments.shape)
print("AISLES :",aisles.shape)
print("PRIOR :",prior.shape)
print("TRAIN :",train.shape)

ORDERS : (3421083, 7)
PRODUCTS : (49688, 4)
DEPARTMENTS : (21, 2)
AISLES : (134, 2)
PRIOR : (32434489, 4)
TRAIN : (1384617, 4)

In [205]:
print("ORDERS :",orders.columns.tolist())
print("PRODUCTS :",products.columns.tolist())
print("DEPARTMENTS :",departments.columns.tolist())
print("AISLES :",aisles.columns.tolist())
print("PRIOR :",prior.columns.tolist())
print("TRAIN :",train.columns.tolist())

ORDERS : ['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']
PRODUCTS : ['product_id', 'product_name', 'aisle_id', 'department_id']
DEPARTMENTS : ['department_id', 'department']
AISLES : ['aisle_id', 'aisle']
PRIOR : ['order_id', 'product_id', 'add_to_cart_order', 'reordered']
TRAIN : ['order_id', 'product_id', 'add_to_cart_order', 'reordered']

In [206]:
print("**ORDERS**")
print(orders.isnull().sum())
print("\n**PRODUCTS**")
print(products.isnull().sum())
print("\n**DEPARTMENTS**")
print(departments.isnull().sum())
print("\n**AISLES**")
print(aisles.isnull().sum())

**ORDERS**
order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

**PRODUCTS**
product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

**DEPARTMENTS**
department_id    0
department       0
dtype: int64

**AISLES**
aisle_id    0
aisle       0
dtype: int64

In [180]:
print("ORDERS duplicates:", orders.duplicated().sum())
print("PRODUCTS duplicates:", products.duplicated().sum())
print("DEPARTMENTS duplicates:", departments.duplicated().sum())
print("AISLES duplicates:", aisles.duplicated().sum())

ORDERS duplicates: 0
PRODUCTS duplicates: 0
DEPARTMENTS duplicates: 0
AISLES duplicates: 0

In [158]:
orders[['order_number', 'order_dow', 'order_hour_of_day','days_since_prior_order']].describe()

       order_number     order_dow  order_hour_of_day  days_since_prior_order
count  3.421083e+06  3.421083e+06       3.421083e+06            3.214874e+06
mean   1.715486e+01  2.776219e+00       1.345202e+01            1.111484e+01
std    1.773316e+01  2.046829e+00       4.226088e+00            9.206737e+00
min    1.000000e+00  0.000000e+00       0.000000e+00            0.000000e+00
25%    5.000000e+00  1.000000e+00       1.000000e+01            4.000000e+00
50%    1.100000e+01  3.000000e+00       1.300000e+01            7.000000e+00
75%    2.300000e+01  5.000000e+00       1.600000e+01            1.500000e+01
max    1.000000e+02  6.000000e+00       2.300000e+01            3.000000e+01

In [159]:
orders['order_number'].max()

100

In [160]:
orders['order_dow'].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [161]:
day_orders = orders['order_dow'].value_counts().sort_index()
day_percentage = (day_orders/len(orders)*100).round(2)
print(day_percentage)

order_dow
0    17.56
1    17.17
2    13.66
3    12.77
4    12.46
5    13.25
6    13.12
Name: count, dtype: float64

In [162]:
hour_orders = orders["order_hour_of_day"].value_counts().sort_index()
hour_percentage = (hour_orders/len(orders)*100).round(2)
print(hour_percentage)

order_hour_of_day
0     0.67
1     0.36
2     0.22
3     0.16
4     0.16
5     0.28
6     0.89
7     2.69
8     5.21
9     7.54
10    8.43
11    8.32
12    7.98
13    8.13
14    8.27
15    8.29
16    7.97
17    6.69
18    5.35
19    4.11
20    3.05
21    2.28
22    1.80
23    1.17
Name: count, dtype: float64

In [163]:
customer_order_summary = customer_orders.value_counts().sort_index()
print(customer_order_summary.head(20))

order_number
4     23986
5     19590
6     16165
7     13850
8     11700
9     10190
10     9032
11     7815
12     6952
13     6236
14     5613
15     5191
16     4593
17     4139
18     3836
19     3390
20     3200
21     2921
22     2706
23     2605
Name: count, dtype: int64

In [164]:
print("Customers with only one order:", (customer_orders == 1).sum())
print("Customers with more than one orders:", (customer_orders >= 2).sum())

Customers with only one order: 0
Customers with more than one orders: 206209

In [165]:
order_retention = orders.groupby('order_number')['user_id'].nunique()
retention_percentage = (order_retention / orders['user_id'].nunique() * 100).round(2)
print(retention_percentage.head(15))

order_number
1     100.00
2     100.00
3     100.00
4     100.00
5      88.37
6      78.87
7      71.03
8      64.31
9      58.64
10     53.70
11     49.32
12     45.53
13     42.16
14     39.13
15     36.41
Name: user_id, dtype: float64

In [166]:
top_products = (prior['product_id'].value_counts().head(10))
print(top_products)

product_id
24852    472565
13176    379450
21137    264683
21903    241921
47209    213584
47766    176815
47626    152657
16797    142951
26209    140627
27845    137905
Name: count, dtype: int64

In [167]:
top_product_ids = prior['product_id'].value_counts().head(10).index
top_products = products[products['product_id'].isin(top_product_ids)].copy()
top_products

       product_id            product_name  aisle_id  department_id
13175       13176  Bag of Organic Bananas        24              4
16796       16797            Strawberries        24              4
21136       21137    Organic Strawberries        24              4
21902       21903    Organic Baby Spinach       123              4
24851       24852                  Banana        24              4
26208       26209                   Limes        24              4
27844       27845      Organic Whole Milk        84             16
47208       47209    Organic Hass Avocado        24              4
47625       47626             Large Lemon        24              4
47765       47766         Organic Avocado        24              4

In [168]:
product_counts = prior['product_id'].value_counts().reset_index()
product_counts.columns = ['product_id', 'purchase_count']
top_products = (product_counts .head(10).merge(products, on='product_id', how='left'))

top_products[['product_id', 'product_name', 'purchase_count']]

   product_id            product_name  purchase_count
0       24852                  Banana          472565
1       13176  Bag of Organic Bananas          379450
2       21137    Organic Strawberries          264683
3       21903    Organic Baby Spinach          241921
4       47209    Organic Hass Avocado          213584
5       47766         Organic Avocado          176815
6       47626             Large Lemon          152657
7       16797            Strawberries          142951
8       26209                   Limes          140627
9       27845      Organic Whole Milk          137905

In [169]:
print(prior.shape)

(32434489, 4)

In [170]:
test = prior.merge(
    products[['product_id', 'department_id']],
    on='product_id',
    how='left'
)

print(test.shape)
print(test.head())

(32434489, 5)
   order_id  product_id  add_to_cart_order  reordered  department_id
0         2       33120                  1          1             16
1         2       28985                  2          1              4
2         2        9327                  3          0             13
3         2       45918                  4          1             13
4         2       30035                  5          0             13

In [208]:
test = test.drop(columns=['department_x'])
test = test.rename(columns={'department_y': 'department'})
print(test.head())

KeyError: "['department_x'] not found in axis"

In [172]:
department_purchases = test['department'].value_counts()
print(department_purchases.head(10))

KeyError: 'department'

In [173]:
reorder_rate = prior['reordered'].mean() * 100
print(f"Overall reorder rate: {reorder_rate:.2f}%")

Overall reorder rate: 58.97%

In [181]:
orders[['order_id', 'user_id', 'order_dow', 'order_hour_of_day']].head()

   order_id  user_id  order_dow  order_hour_of_day
0   2539329        1          2                  8
1   2398795        1          3                  7
2    473747        1          3                 12
3   2254736        1          4                  7
4    431534        1          4                 15

In [182]:
order_info = orders[['order_id', 'user_id', 'order_dow', 'order_hour_of_day']]
order_product_data = prior.merge(
    order_info,
    on='order_id',
    how='left'
)
print(order_product_data.shape)
print(order_product_data.head())

(32434489, 7)
   order_id  product_id  add_to_cart_order  reordered  user_id  order_dow  \
0         2       33120                  1          1   202279          5
1         2       28985                  2          1   202279          5
2         2        9327                  3          0   202279          5
3         2       45918                  4          1   202279          5
4         2       30035                  5          0   202279          5

   order_hour_of_day
0                  9
1                  9
2                  9
3                  9
4                  9

In [183]:
hourly_orders = (order_product_data.groupby('order_hour_of_day')['order_id'].nunique().sort_values(ascending=False))
print(hourly_orders.head(10))

order_hour_of_day
10    271885
11    268006
15    266132
14    265556
13    261174
12    256206
16    255949
9     243496
17    214080
18    170998
Name: order_id, dtype: int64

In [184]:
customer_frequency = orders.groupby('user_id')['order_number'].max()
print(customer_frequency.describe())

count    206209.000000
mean         16.590367
std          16.654774
min           4.000000
25%           6.000000
50%          10.000000
75%          20.000000
max         100.000000
Name: order_number, dtype: float64

In [185]:
customer_segments = pd.cut(
    customer_frequency,
    bins=[3, 6, 20, 100],
    labels=['Low Frequency', 'Medium Frequency', 'High Frequency']
)
print(customer_segments.value_counts())

order_number
Medium Frequency    95737
Low Frequency       59741
High Frequency      50731
Name: count, dtype: int64

In [186]:
segment_percentage = (customer_segments.value_counts(normalize=True) * 100).round(2)
print(segment_percentage)

order_number
Medium Frequency    46.43
Low Frequency       28.97
High Frequency      24.60
Name: proportion, dtype: float64

In [187]:
orders['segment'] = orders['user_id'].map(customer_segments)
print(orders[['user_id', 'segment']].head())

   user_id           segment
0        1  Medium Frequency
1        1  Medium Frequency
2        1  Medium Frequency
3        1  Medium Frequency
4        1  Medium Frequency

In [188]:
order_segments = orders[['order_id', 'segment']]

In [189]:
reorder_by_order = (prior.groupby('order_id')['reordered'].mean())

In [190]:
order_reorder = pd.DataFrame({'reorder_rate': reorder_by_order}).reset_index()
order_reorder = order_reorder.merge(
    order_segments,
    on='order_id',
    how='left')
print(order_reorder.head())

   order_id  reorder_rate           segment
0         2      0.666667  Medium Frequency
1         3      1.000000    High Frequency
2         4      0.923077    High Frequency
3         5      0.807692    High Frequency
4         6      0.000000  Medium Frequency

In [191]:
segment_reorder = (order_reorder.groupby('segment')['reorder_rate'].mean().mul(100).round(2))
print(segment_reorder)

segment
Low Frequency       27.74
Medium Frequency    48.57
High Frequency      69.57
Name: reorder_rate, dtype: float64

C:\Users\lavanya\AppData\Local\Temp\ipykernel_9532\2253640702.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  segment_reorder = (order_reorder.groupby('segment')['reorder_rate'].mean().mul(100).round(2))

In [192]:
customer_segment_lookup = (orders[['user_id', 'segment']].drop_duplicates())
print(customer_segment_lookup.shape)
print(customer_segment_lookup.head())

(206209, 2)
    user_id           segment
0         1  Medium Frequency
11        2  Medium Frequency
26        3  Medium Frequency
39        4     Low Frequency
45        5     Low Frequency

In [193]:
segment_summary = (customer_segment_lookup.groupby('segment', observed=True).size().reset_index(name='customers'))
segment_summary['percentage'] = (
    segment_summary['customers']
    / segment_summary['customers'].sum()
    * 100
).round(2)

print(segment_summary)

            segment  customers  percentage
0     Low Frequency      59741       28.97
1  Medium Frequency      95737       46.43
2    High Frequency      50731       24.60

In [194]:
gc.collect()

1796

In [218]:
orders['segment'] = orders['user_id'].map(customer_segments)

print(orders[['user_id', 'segment']].head())

print("Done")

   user_id           segment
0        1  Medium Frequency
1        1  Medium Frequency
2        1  Medium Frequency
3        1  Medium Frequency
4        1  Medium Frequency
Done

In [219]:
order_segments = orders[['order_id', 'segment']]

print(order_segments.head())

   order_id           segment
0   2539329  Medium Frequency
1   2398795  Medium Frequency
2    473747  Medium Frequency
3   2254736  Medium Frequency
4    431534  Medium Frequency

In [224]:
prior = pd.read_csv(
    "order_products__prior.csv",
    usecols=['order_id', 'product_id', 'reordered']
)

In [225]:
customer_frequency = orders.groupby('user_id')['order_number'].max()

customer_segments = pd.cut(
    customer_frequency,
    bins=[3, 6, 20, 100],
    labels=['Low Frequency', 'Medium Frequency', 'High Frequency']
)

orders['segment'] = orders['user_id'].map(customer_segments)

In [226]:
print(orders.shape)
print(prior.shape)

(3421083, 8)
(32434489, 3)

In [229]:
product_reorder = (prior.groupby('product_id')['reordered'].mean().sort_values(ascending=False))
print(product_reorder.head(10))

product_id
6433     0.941176
2075     0.931034
43553    0.923077
27740    0.920792
14609    0.914286
13875    0.911111
39992    0.909091
5868     0.900000
31418    0.900000
35604    0.900000
Name: reordered, dtype: float64

In [230]:
product_stats = (
    prior.groupby('product_id')
    .agg(
        purchases=('reordered', 'count'),
        reorder_rate=('reordered', 'mean')
    )
)

product_stats = product_stats[
    product_stats['purchases'] >= 1000
]

product_stats['reorder_rate'] = (
    product_stats['reorder_rate'] * 100
).round(2)

print(
    product_stats
    .sort_values('reorder_rate', ascending=False)
    .head(10)
)

            purchases  reorder_rate
product_id
9292             2921         86.17
45504            9108         86.02
43394            8477         85.90
5514             3970         85.77
47231            1489         85.76
29447           20198         85.43
38689           35663         85.07
34197            5185         85.00
24852          472565         84.35
31720            9842         84.12

In [231]:
top_reorder_products = (
    product_stats
    .sort_values('reorder_rate', ascending=False)
    .head(10)
    .reset_index()
)

top_reorder_products = top_reorder_products.merge(
    products[['product_id', 'product_name']],
    on='product_id',
    how='left'
)

print(
    top_reorder_products[
        ['product_id', 'product_name', 'purchases', 'reorder_rate']
    ]
)

   product_id                     product_name  purchases  reorder_rate
0        9292  Half And Half Ultra Pasteurized       2921         86.17
1       45504       Whole Organic Omega 3 Milk       9108         86.02
2       43394  Organic Lactose Free Whole Milk       8477         85.90
3        5514   Organic Homogenized Whole Milk       3970         85.77
4       47231             Ultra-Purified Water       1489         85.76
5       29447         Milk, Organic, Vitamin D      20198         85.43
6       38689         Organic Reduced Fat Milk      35663         85.07
7       34197                        Goat Milk       5185         85.00
8       24852                           Banana     472565         84.35
9       31720              Organic  Whole Milk       9842         84.12

In [233]:
prior_cart = pd.read_csv(
    "order_products__prior.csv",
    usecols=['order_id', 'add_to_cart_order']
)

In [234]:
order_size = (
    prior_cart.groupby('order_id')['add_to_cart_order']
    .max()
)

print(order_size.describe())

count    3.214874e+06
mean     1.008888e+01
std      7.525398e+00
min      1.000000e+00
25%      5.000000e+00
50%      8.000000e+00
75%      1.400000e+01
max      1.450000e+02
Name: add_to_cart_order, dtype: float64

In [235]:
total_orders = orders['order_id'].nunique()
total_customers = orders['user_id'].nunique()
total_products = products['product_id'].nunique()
avg_products_per_order = order_size.mean()
overall_reorder_rate = prior['reordered'].mean() * 100

print("Total Orders:", f"{total_orders:,}")
print("Total Customers:", f"{total_customers:,}")
print("Total Products:", f"{total_products:,}")
print("Avg Products per Order:", round(avg_products_per_order, 2))
print("Overall Reorder Rate:", round(overall_reorder_rate, 2), "%")

Total Orders: 3,421,083
Total Customers: 206,209
Total Products: 49,688
Avg Products per Order: 10.09
Overall Reorder Rate: 58.97 %